// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaji2cN1TSfv5AsrToww0tDMz_X24_TFI',
    appId: '1:102290354167:web:5c7ae444ea55449de8c8f2',
    messagingSenderId: '102290354167',
    projectId: 'ai-hack26ham-435',
    authDomain: 'ai-hack26ham-435.firebaseapp.com',
    storageBucket: 'ai-hack26ham-435.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcGcdrTmwCI6Jg-bNOGg3Zh1xZiNH8ez0',
    appId: '1:102290354167:android:7bf70f9ec1c5daaae8c8f2',
    messagingSenderId: '102290354167',
    projectId: 'ai-hack26ham-435',
    storageBucket: 'ai-hack26ham-435.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB59x7SpEMux9TI9PJkZlZaYMzuhRwtbNI',
    appId: '1:102290354167:ios:f2c2f84549e4bf2ce8c8f2',
    messagingSenderId: '102290354167',
    projectId: 'ai-hack26ham-435',
    storageBucket: 'ai-hack26ham-435.firebasestorage.app',
    iosBundleId: 'com.bcgplatinion.longevity.longevityCompass',
  );
}
